<a href="https://colab.research.google.com/github/moodenaresh1902/demo-repo/blob/main/forwardpass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
####adding layer using 'for' loop
import numpy as np
inputs = [1, 2, 3, 2.5]

##LIST OF WEIGHTS
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

##LIST OF BIASES
biases = [2, 3, 0.5]

layer_outputs = []

for neuron_weights, neuron_bias in zip(weights,biases):
  neuron_output = 0
  for n_inputs,n_weights in zip(inputs,neuron_weights):
    neuron_output+=(n_inputs*n_weights)
  neuron_output+=neuron_bias

  layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


DENSE LAYER CLASS

In [5]:
!pip install nnfs
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
import numpy as np

class Dense_Layer:
  def __init__(self,n_inputs,n_neurons):
    self.weights = np.random.randn(n_inputs,n_neurons)
    self.baises = np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output = np.dot(inputs,self.weights)+self.baises

X,y = spiral_data(samples=100,classes=3)
dense1 = Dense_Layer(2,3)
dense1.forward(X)
print(dense1.output[:5])

class Activation_ReLU:
  def forward(self,inputs):
    self.output = np.maximum(0,inputs)

activation1 = Activation_ReLU()
activation1.forward(dense1.output)
print(activation1.output[:5])

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.04751885e-02  1.13953613e-02 -4.79835039e-03]
 [-2.74148434e-02  3.17291506e-02 -8.69217981e-03]
 [-4.21883687e-02  5.26662543e-02 -5.59126865e-03]
 [-5.77076823e-02  7.14014024e-02 -8.94304458e-03]
 [-3.54306996e-02  3.50254886e-02 -2.33634822e-02]
 [-8.92670080e-02  1.07678764e-01 -1.94532368e-02]
 [-9.33507830e-02  1.07238024e-01 -3.12273987e-02]
 [-1.12437591e-01  1.31128013e-01 -3.36296745e-02]
 [-1.33869559e-01  1.62009060e-01 -2.81017963e-02]
 [-1.48779735e-01  1.79484233e-01 -3.23859528e-02]
 [-1.20035879e-01  1.58119112e-01  8.65936803e-04]
 [-1.56528324e-01  1.99173316e-01 -1.30997356e-02]
 [-1.85718179e-01  2.30642661e-01 -2.70479396e-02]
 [-1.78093582e-01  2.27836683e-01 -1.24245724e-02]
 [-1.85300544e-01  2.38476768e-01 -1.00471666e-02]
 [-6.99865147e-02  1.11472741e-01  3.96097898e-02]
 [-2.19024271e-01  2.79446483e-01 -1.68075711e-02]
 [-1.69829145e-01  2.29598463e-01  1.31671680e-02]
 [-2.60229021e-01  3.27291906e-